version: "3.9"

services:
  db:
    image: mariadb:10.6
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: c2550550_wordpre
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wpsecret
      MYSQL_ROOT_PASSWORD: rootsecret
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./bd.sql:/docker-entrypoint-initdb.d/10-import.sql:ro
      - ./docker/sql/20-replace-url.sql:/docker-entrypoint-initdb.d/20-replace-url.sql:ro

  wordpress:
    image: wordpress:6.8.3-php8.2-apache
    depends_on:
      - db
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wpsecret
      WORDPRESS_DB_NAME: c2550550_wordpre
    ports:
      - "8080:80"
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./wp-config.php:/var/www/html/wp-config.php
      - ./imagenes:/var/www/html/imagenes
      - ./logoCyc.png:/var/www/html/logoCyc.png

  wpcli:
    image: wordpress:cli-php8.2
    depends_on:
      - wordpress
    entrypoint: ["bash","/var/www/html/wp-content/cli-init.sh"]
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wpsecret
      WORDPRESS_DB_NAME: c2550550_wordpre
    volumes:
      - ./wp-content:/var/www/html/wp-content

volumes:
  db_data:



