services:
  db:
    image: mariadb:10.6
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: c2550550_wordpre
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wpsecret
      MYSQL_ROOT_PASSWORD: rootsecret
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    image: wordpress:6.8.3-php8.2-apache
    depends_on:
      - db
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wpsecret
      WORDPRESS_DB_NAME: c2550550_wordpre
    ports:
      - "8080:80"
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./imagenes:/var/www/html/imagenes
      - wordpress_data:/var/www/html

volumes:
  db_data:
  wordpress_data:



